# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [2]:
print(np.version.version)

2.2.4


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [11]:
from random import randint, random
#method 1
a = np.random.randint(10, size = (2,3,5))
print("A is an array of the following numbers: ")
print(a.ndim)
print(a)

#method 2
a2 = np.random.rand(2,3,5)
print("A2 is an array of the following numbers: ")
print(a2.ndim)
print(a2)

#method 3
a3 = np.random.randn(2,3,5)
print("A3 is an array of the following numbers: ")
print(a3.ndim)
print(a3)

A is an array of the following numbers: 
3
[[[4 2 8 9 9]
  [9 0 6 6 8]
  [3 3 4 8 5]]

 [[9 3 5 4 4]
  [8 1 4 5 5]
  [4 2 3 2 8]]]
A2 is an array of the following numbers: 
3
[[[0.58705264 0.10439797 0.10987155 0.87880466 0.19634468]
  [0.01690683 0.90795606 0.46336664 0.29963763 0.22100271]
  [0.64851394 0.07692552 0.87480797 0.77126095 0.9695411 ]]

 [[0.40088819 0.1784533  0.48114638 0.22217642 0.75097671]
  [0.7116865  0.12059496 0.32261741 0.4235361  0.78969466]
  [0.17073756 0.11060123 0.13605561 0.33102555 0.2068833 ]]]
A3 is an array of the following numbers: 
3
[[[ 0.5121003  -0.46159845  1.61143687  0.40841123  0.20668906]
  [ 0.98682028 -0.47623397 -1.72452115  0.03894566  0.12958093]
  [ 1.62019624  0.92710677 -0.18568419 -1.70274415  1.14417101]]

 [[ 0.47493394 -2.08219872 -0.04255597  0.17259219 -0.77573742]
  [-1.19144815  0.82735278  1.83961642  1.30307053  1.66074257]
  [ 0.3060472  -0.87736169 -1.96939736  0.46438388 -0.84827314]]]



### 4. Print a.


In [12]:
print(a)
print(a2)
print(a3)

[[[4 2 8 9 9]
  [9 0 6 6 8]
  [3 3 4 8 5]]

 [[9 3 5 4 4]
  [8 1 4 5 5]
  [4 2 3 2 8]]]
[[[0.58705264 0.10439797 0.10987155 0.87880466 0.19634468]
  [0.01690683 0.90795606 0.46336664 0.29963763 0.22100271]
  [0.64851394 0.07692552 0.87480797 0.77126095 0.9695411 ]]

 [[0.40088819 0.1784533  0.48114638 0.22217642 0.75097671]
  [0.7116865  0.12059496 0.32261741 0.4235361  0.78969466]
  [0.17073756 0.11060123 0.13605561 0.33102555 0.2068833 ]]]
[[[ 0.5121003  -0.46159845  1.61143687  0.40841123  0.20668906]
  [ 0.98682028 -0.47623397 -1.72452115  0.03894566  0.12958093]
  [ 1.62019624  0.92710677 -0.18568419 -1.70274415  1.14417101]]

 [[ 0.47493394 -2.08219872 -0.04255597  0.17259219 -0.77573742]
  [-1.19144815  0.82735278  1.83961642  1.30307053  1.66074257]
  [ 0.3060472  -0.87736169 -1.96939736  0.46438388 -0.84827314]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [13]:
b = np.ones((5,2,3))



### 6. Print b.


In [14]:
### [your code here]
print("B is an array of the following numbers: ")
print(b)

B is an array of the following numbers: 
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [15]:
if a.ndim == b.ndim:
    print("A and B have the same number of dimensions")
elif a.shape == b.shape:
    print("A and B have the same shape")
elif a.size == b.size:
    print("A and B have the same size")

A and B have the same number of dimensions



### 8. Are you able to add a and b? Why or why not?


In [ ]:
# We are not able to add a and b as they are not the same shape 

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [20]:
arrayb1d = np.array(b)
print(arrayb1d)
c = np.reshape(arrayb1d, (2,3,5))
print("C is an array of the following numbers: ")
print(c)
print(a + c)



[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
C is an array of the following numbers: 
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
[[[ 5.  3.  9. 10. 10.]
  [10.  1.  7.  7.  9.]
  [ 4.  4.  5.  9.  6.]]

 [[10.  4.  6.  5.  5.]
  [ 9.  2.  5.  6.  6.]
  [ 5.  3.  4.  3.  9.]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [21]:
d = a + c



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [ ]:
print(a)
print(d)

#D is an array of the same shape as A, with each value + 1, because the original array that we added to it (b) was an array of ones.

[[[4 2 8 9 9]
  [9 0 6 6 8]
  [3 3 4 8 5]]

 [[9 3 5 4 4]
  [8 1 4 5 5]
  [4 2 3 2 8]]]
[[[ 5.  3.  9. 10. 10.]
  [10.  1.  7.  7.  9.]
  [ 4.  4.  5.  9.  6.]]

 [[10.  4.  6.  5.  5.]
  [ 9.  2.  5.  6.  6.]
  [ 5.  3.  4.  3.  9.]]]



### 12. Multiply a and c. Assign the result to e.


In [24]:
e = a * c
print("E is an array created by multiplying A and C: ")
print(e)


E is an array created by multiplying A and C: 
[[[4. 2. 8. 9. 9.]
  [9. 0. 6. 6. 8.]
  [3. 3. 4. 8. 5.]]

 [[9. 3. 5. 4. 4.]
  [8. 1. 4. 5. 5.]
  [4. 2. 3. 2. 8.]]]




### 13. Does e equal to a? Why or why not?


In [28]:
if e.all() == a.all():
    print("E is the same as A, because c consists of ones only")
else:
    print("E is not the same as A")


E is the same as A, because c consists of ones only




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [32]:
d_max = d.max()
print("Max value in d =", d_max)
d_min = d.min()
print("Min value in d =", d_min)
d_mean = d.mean()
print("Mean value in d =", d_mean)



Max value in d = 10.0
Min value in d = 1.0
Mean value in d = 6.033333333333333



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [33]:
f = np.empty((2,3,5))
print("F is an empy array of the shape 2x3x5")


F is an empy array of the shape 2x3x5





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [39]:
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            # Get the current value
            value = d[i, j, k]
            
            # Apply conditions and update f
            if value > d_min and value < d_mean:
                f[i, j, k] = 25
            elif value > d_mean and value < d_max:
                f[i, j, k] = 75
            elif value == d_mean:
                f[i, j, k] = 50
            elif value == d_max:
                f[i, j, k] = 100
                






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [40]:
print("\nD array (original):")
print(d)
print("\nF is an array of the following numbers:")
print(f)


D array (original):
[[[ 5.  3.  9. 10. 10.]
  [10.  1.  7.  7.  9.]
  [ 4.  4.  5.  9.  6.]]

 [[10.  4.  6.  5.  5.]
  [ 9.  2.  5.  6.  6.]
  [ 5.  3.  4.  3.  9.]]]

F is an array of the following numbers:
[[[ 25.  25.  75. 100. 100.]
  [100.   0.  75.  75.  75.]
  [ 25.  25.  25.  75.  25.]]

 [[100.  25.  25.  25.  25.]
  [ 75.  25.  25.  25.  25.]
  [ 25.  25.  25.  25.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [46]:
fs = f.astype(str)

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            # Get the current value
            value = d[i, j, k]
            
            # Apply conditions and update f
            if value > d_min and value < d_mean:
                fs[i, j, k] = "A"
            elif value > d_mean and value < d_max:
                fs[i, j, k] = "C"
            elif value == d_mean:
                fs[i, j, k] = "B"
            elif value == d_max:
                fs[i, j, k] = "D"
                
print(d)
print(f)
print(fs)

[[[ 5.  3.  9. 10. 10.]
  [10.  1.  7.  7.  9.]
  [ 4.  4.  5.  9.  6.]]

 [[10.  4.  6.  5.  5.]
  [ 9.  2.  5.  6.  6.]
  [ 5.  3.  4.  3.  9.]]]
[[[ 25.  25.  75. 100. 100.]
  [100.   0.  75.  75.  75.]
  [ 25.  25.  25.  75.  25.]]

 [[100.  25.  25.  25.  25.]
  [ 75.  25.  25.  25.  25.]
  [ 25.  25.  25.  25.  75.]]]
[[['A' 'A' 'C' 'D' 'D']
  ['D' '0.0' 'C' 'C' 'C']
  ['A' 'A' 'A' 'C' 'A']]

 [['D' 'A' 'A' 'A' 'A']
  ['C' 'A' 'A' 'A' 'A']
  ['A' 'A' 'A' 'A' 'C']]]
